In [3]:
import numpy as np
import pandas as pd
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr1)
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print("\nExercise 2:\n", extracted_elements)
 Exercise 3: Create a Pandas series and add a new item
series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series['pears'] = 4
print("\nExercise 3:\n", series)

# Exercise 4: Create a dataframe with columns: name, age, gender
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [25, 32, 28, 45, 39, 22, 41, 30, 26, 50],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("\nExercise 4:\n", df)

# Exercise 5: Add an occupation column
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("\nExercise 5:\n", df)

# Exercise 6: Select rows where age is >= 30
df_filtered = df[df['age'] >= 30]
print("\nExercise 6:\n", df_filtered)

# Exercise 7: Save dataframe to CSV and read it back
csv_file_path = "dataframe.csv"
df.to_csv(csv_file_path, index=False)

df_read = pd.read_csv(csv_file_path)
print("\nExercise 7:\n", df_read)



IndentationError: unexpected indent (3105621844.py, line 8)

In [ ]:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

In [ ]:
[ 6  7  8  9 10 11 12 13 14 15 16]

In [ ]:
apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [9]:
     name     age  gender  occupation
0   Person1   25    Male  Programmer
1   Person2   28  Female     Manager
2   Person3   27    Male     Analyst
3   Person4   38  Female  Programmer
4   Person5   34    Male     Manager
5   Person6   35  Female     Analyst
6   Person7   20    Male  Programmer
7   Person8   47  Female     Manager
8   Person9   39    Male     Analyst
9  Person10   46  Female  Programmer

SyntaxError: invalid syntax (3613066023.py, line 1)

In [ ]:
name  age  gender  occupation
3   Person4   38  Female  Programmer
4   Person5   34    Male     Manager
5   Person6   35  Female     Analyst
7   Person8   47  Female     Manager
8   Person9   39    Male     Analyst
9  Person10   46  Female  Programmer